"""ReplayBuffer: synthetic examples for the fast mechanics, ONE real (net-free)
replay for state re-derivation. No self-play here -- see test_selfplay for that."""

from __future__ import annotations

import random
from pathlib import Path

import pytest

from carcassonne.agents import RandomAgent
from carcassonne.game.match import play_game
from carcassonne.game.replay import load_replay, replay_states
from carcassonne.nn.actions import ACTION_SPACE
from carcassonne.training.buffer import Example, ReplayBuffer, SampledExample


def _example(move_n: int, value: float) -> Example:
    # sparse policy over two valid action ids, summing to 1.
    return Example(move_n=move_n, policy={5: 0.25, 6: 0.75}, value=value)


def _populate(buf: ReplayBuffer) -> None:
    buf.add_game("g0", "replays/g0.jsonl", [_example(0, 1.0), _example(1, -1.0)], order_key=0)
    buf.add_game("g1", "replays/g1.jsonl", [_example(0, 0.0)], order_key=1)


def test_add_len_and_sample(tmp_path: Path) -> None:
    buf = ReplayBuffer(tmp_path / "b.sqlite")
    _populate(buf)
    assert len(buf) == 3
    assert buf.n_games() == 2

    batch = buf.sample(20, random.Random(0))
    assert len(batch) == 20
    for ex in batch:
        assert isinstance(ex, SampledExample)
        assert ex.policy  # non-empty sparse dict
        assert sum(ex.policy.values()) == pytest.approx(1.0)
        assert ex.value in (-1.0, 0.0, 1.0)
        for action_id in ex.policy:
            assert isinstance(action_id, int)
            assert 0 <= action_id < ACTION_SPACE

    # deterministic for a given seed + buffer contents
    assert buf.sample(20, random.Random(0)) == buf.sample(20, random.Random(0))
    buf.close()


def test_sample_empty_raises(tmp_path: Path) -> None:
    buf = ReplayBuffer(tmp_path / "b.sqlite")
    with pytest.raises(ValueError):
        buf.sample(4, random.Random(0))
    buf.close()


def test_state_for_matches_replay_and_is_lru_cached(tmp_path: Path) -> None:
    # ONE real replay, generated by a net-free random-agent game (fast).
    replay_dir = tmp_path / "replays"
    result = play_game((RandomAgent(), RandomAgent()), seed=7, replay_dir=replay_dir)
    assert result.replay_path is not None
    replay = load_replay(result.replay_path)
    reference = list(replay_states(replay))  # states before each move, then terminal
    n_moves = len(replay.moves)

    buf = ReplayBuffer(tmp_path / "b.sqlite")
    buf.add_game(
        "real",
        str(result.replay_path),
        [_example(k, 0.0) for k in range(n_moves)],
        order_key=0,
    )

    for k in (0, n_moves // 2, n_moves):
        state = buf.state_for("real", k)
        assert state.board == reference[k].board
        assert state.scores == reference[k].scores
        assert state.current_player == reference[k].current_player

    # LRU: repeated re-derivation returns the very same cached objects.
    assert buf.state_for("real", 1) is buf.state_for("real", 1)
    buf.close()


def test_state_for_unknown_game_raises(tmp_path: Path) -> None:
    buf = ReplayBuffer(tmp_path / "b.sqlite")
    with pytest.raises(KeyError):
        buf.state_for("nope", 0)
    buf.close()


def test_evict_to_drops_oldest_by_order_key(tmp_path: Path) -> None:
    buf = ReplayBuffer(tmp_path / "b.sqlite")
    buf.add_game("old", "p0", [_example(0, 0.0)], order_key=0)
    buf.add_game("mid", "p1", [_example(0, 0.0)], order_key=1)
    buf.add_game("new", "p2", [_example(0, 0.0)], order_key=2)

    deleted = buf.evict_to(1)
    assert deleted == 2
    assert buf.n_games() == 1
    assert len(buf) == 1
    # the survivor is the newest (largest order_key); its examples remain.
    assert buf.state_for is not None  # sanity
    with pytest.raises(KeyError):
        buf.state_for("old", 0)
    # no-op when already within the window
    assert buf.evict_to(5) == 0
    buf.close()


def test_persistence_across_reopen(tmp_path: Path) -> None:
    path = tmp_path / "b.sqlite"
    buf = ReplayBuffer(path)
    _populate(buf)
    buf.close()

    reopened = ReplayBuffer(path)
    assert len(reopened) == 3
    assert reopened.n_games() == 2
    batch = reopened.sample(5, random.Random(1))
    assert all(sum(ex.policy.values()) == pytest.approx(1.0) for ex in batch)
    reopened.close()
